export default {
  tabs: {
    home: 'الرئيسية',
    history: 'السجل',
    profile: 'الملف',
  },

  home: {
    greeting: 'مرحبا',
    tip1: 'نصيحة 1: تأكد من الإضاءة الجيدة لمسح دقيق',
    tip2: 'نصيحة 2: أمسك المستند بثبات وبشكل مسطح',
    tip3: 'نصيحة 3: تأكد أن الحواف ظاهرة بالكامل',
    medicineBtn: 'دواء',
    medicineSub: 'عبوة / شريط',
    reportBtn: 'تقرير',
    reportSub: 'معمل / أشعة',
    quickTips: 'نصائح سريعة',
  },

  camera: {
    whatScanning: 'ماذا تمسح؟',
    medicine: 'دواء',
    medicineSub: 'عبوة، شريط، زجاجة',
    medicineTip: 'اجعل الملصق مستقيماً، إضاءة جيدة، حواف واضحة.',
    medicineFrame: 'ضع عبوة / شريط الدواء داخل الإطار',
    report: 'تقرير مختبر',
    reportSub: 'دم، بول، تقرير مرضي',
    reportTip: 'صفحة واحدة في كل مرة. ورق مسطح، ظل أقل، نص واضح.',
    reportFrame: 'يجب أن تدخل صفحة التقرير كاملة في الإطار',
    xray: 'أشعة / فحص',
    xraySub: 'أشعة، CT، MRI',
    xrayTip: 'فيلم/طباعة على سطح مسطح. تجنب الوهج، غطِ الصورة كاملة.',
    xrayFrame: 'فيلم الأشعة داخل الإطار بالكامل',
    prescription: 'وصفة طبية',
    prescriptionSub: 'وصفة مكتوبة بخط اليد / مطبوعة',
    prescriptionTip: 'صفحة مستقيمة، خط واضح. صفحة واحدة في كل مرة.',
    prescriptionFrame: 'صفحة الوصفة داخل الإطار',
    medicineHint: 'أظهر ملصق الشريط / الزجاجة بوضوح',
    reportHint: 'يجب أن تدخل الصفحة / الفيلم كاملة في الإطار',
    scanMedicine: 'مسح الدواء',
    scanDocument: 'مسح المستند',
    uploadGallery: 'رفع من المعرض',
  },

  result: {
    title: 'نتيجة المسح',
    loading: 'جاري تحضير النتيجة...',
    errorNoImage: 'لم يتم العثور على صورة.',
    errorApiKey: 'مفتاح Gemini API مفقود. عيّن GEMINI_API_KEY في .env',
    errorAnalysis: 'فشل التحليل.',
    errorBlurry: 'مشكلة في الصورة — الصورة غير واضحة.',
    errorMismatchReport: 'يبدو هذا تقرير مختبر / فحص.',
    errorMismatchMedicine: 'يبدو هذا عبوة / شريط دواء.',
    errorChat: 'تعذر معالجة السؤال.',
    chatTitle: 'أسئلتك',
    chatPlaceholderMedicine: 'اسأل عن هذا الدواء...',
    chatPlaceholderReport: 'اسأل عن هذا التقرير...',
    retryNew: 'رفع صورة جديدة',
    retrySame: 'حاول مرة أخرى بنفس الصورة',
    typeMedicine: 'دواء',
    typeReport: 'تقرير مختبر',
    typePrescription: 'وصفة',
    typeOther: 'أخرى',
    match: '% تطابق',
    aboutMedicine: 'عن هذا الدواء',
    aboutReport: 'معنى التقرير ببساطة',
    formulaTitle: 'التركيبة وكيف تعمل',
    formulaLabel: 'التركيبة / الملح',
    howItWorks: 'كيف تعمل هذه التركيبة',
    whyInMedicine: 'لماذا تُستخدم في هذا الدواء',
    howToUse: 'طريقة الاستخدام',
    priceApprox: 'السعر التقريبي: ر.س',
    altIntro: 'نفس / مشابه التركيبة — شركات أخرى (تقريباً)',
    alternatives: 'أدوية بديلة',
    onPackageMedicine: 'مكتوب على العبوة',
    onPackageReport: 'مكتوب على التقرير',
    notesMedicine: 'ملاحظات مهمة',
    notesReport: 'نقاط مهمة',
    unknown: 'غير معروف',
    noScanYet: 'لا يوجد مسح بعد',
  },

  history: {
    tabs: {
      history: 'السجل',
    },
    emptyTitle: 'لا توجد عمليات مسح بعد',
    emptySub: 'امسح دواء أو تقريراً — سيُحفظ هنا',
    deleteTitle: 'حذف المسح؟',
    deleteMessage: '{name}',
    confirmText: 'حذف',
    cancelText: 'إلغاء',
    typeReport: 'تقرير مختبر',
    typePrescription: 'وصفة',
    typeMedicine: 'دواء',
    typeOther: 'أخرى',
    scan: 'مسح',
  },

  profile: {
    title: 'ملفي',
    subtitle: 'الشخصي',
    signedIn: 'مسجّل الدخول',
    guest: 'وضع الضيف',
    totalScans: 'إجمالي المسح',
    language: 'اللغة',
    selectLanguage: 'اختر اللغة',
    settings: 'الإعدادات',
    notifications: 'الإشعارات',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الخدمة',
    rate: 'قيّم التطبيق',
    support: 'الدعم',
    logout: 'تسجيل الخروج',
    logoutConfirm: 'تسجيل الخروج؟',
    logoutMsg: 'سيتم تسجيل خروجك من حسابك.',
    cancel: 'إلغاء',
  },
};