export default {
  home: {
    greeting: 'مرحبا',
    tip1: 'نصيحة 1: تأكد من الإضاءة الجيدة للمسح الدقيق',
    tip2: 'نصيحة 2: امسك المستند ثابتًا ومستويًا',
    tip3: 'نصيحة 3: تأكد من رؤية الحواف بالكامل',
    medicineBtn: 'دواء',
    medicineSub: 'عبوة / شريط',
    reportBtn: 'تقرير',
    reportSub: 'معمل / أشعة',
    quickTips: 'نصائح سريعة',
  },
  camera: {
    whatScanning: 'ما الذي تقوم بمسحه؟',
    medicine: 'دواء',
    medicineSub: 'عبوة، شريط، زجاجة، بليستر',
    medicineTip: '',
    medicineFrame: '',
    report: 'تقرير مختبر',
    reportSub: 'تقرير دم، بول، علم أمراض',
    reportTip: '',
    reportFrame: '',
    xray: 'أشعة / مسح',
    xraySub: 'أشعة، تصوير مقطعي، resonance مغناطيسي طباعة / فيلم',
    xrayTip: '',
    xrayFrame: '',
    prescription: 'وصفة طبية',
    prescriptionSub: 'وصفة يدوية / مطبوعة من الطبيب',
    prescriptionTip: '',
    prescriptionFrame: '',
    medicineHint: 'أظهر ملصق الشريط / الزجاجة بوضوح',
    reportHint: 'يجب أن تناسب الصفحة الكاملة / الفيلم الإطار',
    scanMedicine: 'مسح دواء',
    scanDocument: 'مسح مستند',
    uploadGallery: 'رفع من المعرض',
  },
  result: {
    title: 'نتيجة المسح',
    loading: 'إعداد النتيجة...',
    errorNoImage: 'لم يتم العثور على صورة.',
    errorApiKey: 'مفتاح API لجيميني مفقود. اضبط GEMINI_API_KEY في .env',
    errorAnalysis: 'فشل التحليل.',
    errorBlurry: 'مشكلة في الصورة — الصورة غير واضحة.',
    errorMismatchReport: 'هذا يبدو كتقرير مختبر / اختبار.',
    errorMismatchMedicine: 'هذا يبدو كعبوة دواء / شريط.',
    errorChat: 'لم يتم معالجة السؤال.',
    chatTitle: 'أسئلتك',
    chatPlaceholderMedicine: 'اسأل عن هذا الدواء...',
    chatPlaceholderReport: 'اسأل عن هذا التقرير...',
    retryNew: 'رفع صورة جديدة',
    retrySame: 'المحاولة مرة أخرى بنفس الصورة',
    typeMedicine: 'دواء',
    typeReport: 'تقرير مختبر',
    typePrescription: 'وصفة طبية',
    typeOther: 'آخر',
    match: '% توافق',
    aboutMedicine: 'حول هذا الدواء',
    aboutReport: 'معنى بسيط للتقرير',
    formulaTitle: 'الصيغة وكيفية العمل',
    formulaLabel: 'الصيغة / الملح',
    howItWorks: 'كيف تعمل هذه الصيغة في الجسم',
    whyInMedicine: 'لماذا يستخدم هذا في الدواء',
    howToUse: 'كيفية الاستخدام',
    priceApprox: 'السعر التقريبي: Rs.',
    altIntro: 'صيغة مماثلة — شركات أخرى (تقريبي)',
    alternatives: 'أدوية بديلة',
    onPackageMedicine: 'مكتوب على العبوة',
    onPackageReport: 'مكتوب على التقرير',
    notesMedicine: 'ملاحظات مهمة',
    notesReport: 'نقاط مهمة',
    unknown: 'غير معروف',
    noScanYet: 'لا توجد مسحات بعد',
  },
  history: {
    tabs: {
      history: 'التاريخ',
    },
    emptyTitle: 'لا توجد مسحات بعد',
    emptySub: 'امسح دواء أو تقرير — سيتم حفظه هنا',
    deleteTitle: 'حذف المسح؟',
    deleteMessage: '{name}',
    confirmText: 'حذف',
    cancelText: 'إلغاء',
    typeReport: 'تقرير مختبر',
    typePrescription: 'وصفة طبية',
    typeMedicine: 'دواء',
    typeOther: 'آخر',
    scan: 'مسح',
  },
};