export default {
  home: {
    greeting: 'Hello',
    tip1: 'Tip 1: Ensure good lighting for accurate scans',
    tip2: 'Tip 2: Hold the document steady and flat',
    tip3: 'Tip 3: Check the edges are fully visible',
    medicineBtn: 'Medicine',
    medicineSub: 'Pack / strip',
    reportBtn: 'Report',
    reportSub: 'Lab / X-Ray',
    quickTips: 'Quick Tips',
  },
  camera: {
    whatScanning: 'What are you scanning?',
    medicine: 'Medicine',
    medicineSub: 'Pack, strip, bottle, blister',
    medicineTip: '',
    medicineFrame: '',
    report: 'Lab Report',
    reportSub: 'Blood, urine, pathology report',
    reportTip: '',
    reportFrame: '',
    xray: 'X-Ray / Scan',
    xraySub: 'X-ray, CT, MRI print / film',
    xrayTip: '',
    xrayFrame: '',
    prescription: 'Prescription',
    prescriptionSub: 'Doctor handwritten / printed Rx',
    prescriptionTip: '',
    prescriptionFrame: '',
    medicineHint: 'Show strip / bottle label clearly',
    reportHint: 'Full page / film should fit in the frame',
    scanMedicine: 'Scan Medicine',
    scanDocument: 'Scan Document',
    uploadGallery: 'Upload from Gallery',
  },
  result: {
    title: 'Scan Result',
    loading: 'Preparing result...',
    errorNoImage: 'No image found.',
    errorApiKey: 'Gemini API key missing. Set GEMINI_API_KEY in .env',
    errorAnalysis: 'Analysis failed.',
    errorBlurry: 'Image issue — photo is not clear.',
    errorMismatchReport: 'This looks like a Lab Report / Test.',
    errorMismatchMedicine: 'This looks like a Medicine pack/strip.',
    errorChat: 'Could not process question.',
    chatTitle: 'Your questions',
    chatPlaceholderMedicine: 'Ask about this medicine...',
    chatPlaceholderReport: 'Ask about this report...',
    retryNew: 'Upload new image',
    retrySame: 'Try again with same image',
    typeMedicine: 'Medicine',
    typeReport: 'Lab Report',
    typePrescription: 'Prescription',
    typeOther: 'Other',
    match: '% match',
    aboutMedicine: 'About this medicine',
    aboutReport: 'Simple meaning of report',
    formulaTitle: 'Formula & how it works',
    formulaLabel: 'Formula / salt',
    howItWorks: 'How this formula works',
    whyInMedicine: 'Why it is used in this medicine',
    howToUse: 'How to use',
    priceApprox: 'Approx price: Rs.',
    altIntro: 'Same / similar formula — other companies (approx)',
    alternatives: 'Alternative medicines',
    onPackageMedicine: 'Written on packaging',
    onPackageReport: 'Written on report',
    notesMedicine: 'Important notes',
    notesReport: 'Important points',
    unknown: 'Unknown',
    noScanYet: 'No scan yet',
  },
  history: {
    tabs: {
      history: 'History',
    },
    emptyTitle: 'No scans yet',
    emptySub: 'Scan a medicine or report — it will be saved here',
    deleteTitle: 'Delete scan?',
    deleteMessage: '{name}',
    confirmText: 'Delete',
    cancelText: 'Cancel',
    typeReport: 'Lab Report',
    typePrescription: 'Prescription',
    typeMedicine: 'Medicine',
    typeOther: 'Other',
    scan: 'Scan',
  },
};