export default {
  tabs: {
    home: 'होम',
    history: 'इतिहास',
    profile: 'प्रोफ़ाइल',
  },

  home: {
    greeting: 'नमस्ते',
    tip1: 'टिप 1: सटीक स्कैन के लिए अच्छी रोशनी रखें',
    tip2: 'टिप 2: दस्तावेज़ को सीधा और स्थिर पकड़ें',
    tip3: 'टिप 3: किनारे पूरी तरह दिखाई दें',
    medicineBtn: 'दवा',
    medicineSub: 'पैक / स्ट्रिप',
    reportBtn: 'रिपोर्ट',
    reportSub: 'लैब / एक्स-रे',
    quickTips: 'त्वरित सुझाव',
  },

  camera: {
    whatScanning: 'आप क्या स्कैन कर रहे हैं?',
    medicine: 'दवा',
    medicineSub: 'पैक, स्ट्रिप, बोतल',
    medicineTip: 'लेबल सीधा रखें, अच्छी रोशनी, किनारे साफ़ हों।',
    medicineFrame: 'दवा का पैक / स्ट्रिप फ्रेम के अंदर रखें',
    report: 'लैब रिपोर्ट',
    reportSub: 'खून, पेशाब, पैथोलॉजी रिपोर्ट',
    reportTip: 'एक बार एक पेज। कागज़ सपाट, कम छाया, पाठ साफ़।',
    reportFrame: 'पूरी रिपोर्ट पेज फ्रेम में आनी चाहिए',
    xray: 'एक्स-रे / स्कैन',
    xraySub: 'एक्स-रे, CT, MRI प्रिंट / फिल्म',
    xrayTip: 'फिल्म/प्रिंट सपाट सतह पर। चमक से बचें, पूरी छवि कवर करें।',
    xrayFrame: 'एक्स-रे / स्कैन फिल्म पूरी तरह फ्रेम में',
    prescription: 'नुस्खा',
    prescriptionSub: 'डॉक्टर का हस्तलिखित / प्रिंटेड नुस्खा',
    prescriptionTip: 'पेज सीधा, लिखावट साफ़। एक बार एक पेज।',
    prescriptionFrame: 'नुस्खा पेज फ्रेम के अंदर',
    medicineHint: 'स्ट्रिप / बोतल का लेबल साफ़ दिखाएँ',
    reportHint: 'पूरा पेज / फिल्म फ्रेम के अंदर आए',
    scanMedicine: 'दवा स्कैन करें',
    scanDocument: 'दस्तावेज़ स्कैन करें',
    uploadGallery: 'गैलरी से अपलोड',
  },

  result: {
    title: 'स्कैन परिणाम',
    loading: 'परिणाम तैयार हो रहा है...',
    errorNoImage: 'कोई छवि नहीं मिली।',
    errorApiKey: 'Gemini API key गायब है। .env में GEMINI_API_KEY सेट करें',
    errorAnalysis: 'विश्लेषण विफल।',
    errorBlurry: 'छवि समस्या — फोटो साफ़ नहीं।',
    errorMismatchReport: 'यह लैब रिपोर्ट / टेस्ट लगता है।',
    errorMismatchMedicine: 'यह दवा पैक / स्ट्रिप लगता है।',
    errorChat: 'प्रश्न प्रोसेस नहीं हो सका।',
    chatTitle: 'आपके प्रश्न',
    chatPlaceholderMedicine: 'इस दवा के बारे में पूछें...',
    chatPlaceholderReport: 'इस रिपोर्ट के बारे में पूछें...',
    retryNew: 'नई छवि अपलोड करें',
    retrySame: 'उसी छवि से फिर कोशिश',
    typeMedicine: 'दवा',
    typeReport: 'लैब रिपोर्ट',
    typePrescription: 'नुस्खा',
    typeOther: 'अन्य',
    match: '% मैच',
    aboutMedicine: 'इस दवा के बारे में',
    aboutReport: 'रिपोर्ट का सरल अर्थ',
    formulaTitle: 'फॉर्मूला और यह कैसे काम करता है',
    formulaLabel: 'फॉर्मूला / साल्ट',
    howItWorks: 'यह फॉर्मूला कैसे काम करता है',
    whyInMedicine: 'इस दवा में यह क्यों इस्तेमाल होता है',
    howToUse: 'उपयोग कैसे करें',
    priceApprox: 'अनुमानित कीमत: रु.',
    altIntro: 'समान / मिलता-जुलता फॉर्मूला — अन्य कंपनियाँ (लगभग)',
    alternatives: 'वैकल्पिक दवाएँ',
    onPackageMedicine: 'पैकेजिंग पर लिखा',
    onPackageReport: 'रिपोर्ट पर लिखा',
    notesMedicine: 'महत्वपूर्ण नोट्स',
    notesReport: 'महत्वपूर्ण बातें',
    unknown: 'अज्ञात',
    noScanYet: 'अभी कोई स्कैन नहीं',
  },

  history: {
    tabs: {
      history: 'इतिहास',
    },
    emptyTitle: 'अभी कोई स्कैन नहीं',
    emptySub: 'दवा या रिपोर्ट स्कैन करें — यहाँ सेव हो जाएगी',
    deleteTitle: 'स्कैन हटाएँ?',
    deleteMessage: '{name}',
    confirmText: 'हटाएँ',
    cancelText: 'रद्द',
    typeReport: 'लैब रिपोर्ट',
    typePrescription: 'नुस्खा',
    typeMedicine: 'दवा',
    typeOther: 'अन्य',
    scan: 'स्कैन',
  },

  profile: {
    title: 'मेरा',
    subtitle: 'प्रोफ़ाइल',
    signedIn: 'साइन इन',
    guest: 'गेस्ट मोड',
    totalScans: 'कुल स्कैन',
    language: 'भाषा',
    selectLanguage: 'भाषा चुनें',
    settings: 'सेटिंग्स',
    notifications: 'सूचनाएँ',
    privacy: 'गोपनीयता नीति',
    terms: 'सेवा की शर्तें',
    rate: 'ऐप रेट करें',
    support: 'सहायता',
    logout: 'लॉग आउट',
    logoutConfirm: 'लॉग आउट?',
    logoutMsg: 'आप अपने अकाउंट से साइन आउट हो जाएँगे।',
    cancel: 'रद्द',
  },
};