export default {
  home: {
    greeting: 'नमस्ते',
    tip1: 'सुझाव 1: सटीक स्कैन के लिए अच्छी रोशनी सुनिश्चित करें',
    tip2: 'सुझाव 2: दस्तावेज़ को स्थिर और समतल रखें',
    tip3: 'सुझाव 3: किनारों को पूरी तरह से दिखाई देने दें',
    medicineBtn: 'दवा',
    medicineSub: 'पैक / स्ट्रिप',
    reportBtn: 'रिपोर्ट',
    reportSub: 'लैब / एक्स-रे',
    quickTips: 'त्वरित सुझाव',
  },
  camera: {
    whatScanning: 'आप क्या स्कैन कर रहे हैं?',
    medicine: 'दवा',
    medicineSub: 'पैक, स्ट्रिप, बोतल, ब्लिस्टर',
    medicineTip: '',
    medicineFrame: '',
    report: 'लैब रिपोर्ट',
    reportSub: 'रक्त, मूत्र, पैथोलॉजी रिपोर्ट',
    reportTip: '',
    reportFrame: '',
    xray: 'एक्स-रे / स्कैन',
    xraySub: 'एक्स-रे, सीटी, एमआरआई प्रिंट / फिल्म',
    xrayTip: '',
    xrayFrame: '',
    prescription: 'पर्चे',
    prescriptionSub: 'डॉक्टर का हाथ से लिखा / प्रिंटेड Rx',
    prescriptionTip: '',
    prescriptionFrame: '',
    medicineHint: 'स्ट्रिप / बोतल लेबल स्पष्ट रूप से दिखाएं',
    reportHint: 'पूरा पृष्ठ / फिल्म फ्रेम में फिट होना चाहिए',
    scanMedicine: 'दवा स्कैन करें',
    scanDocument: 'दस्तावेज़ स्कैन करें',
    uploadGallery: 'गैलरी से अपलोड करें',
  },
  result: {
    title: 'स्कैन परिणाम',
    loading: 'परिणाम तैयार किया जा रहा है...',
    errorNoImage: 'कोई छवि नहीं मिली।',
    errorApiKey: 'जेमिनी API कुंजी गायब है। .env में GEMINI_API_KEY सेट करें',
    errorAnalysis: 'विश्लेषण विफल।',
    errorBlurry: 'छवि समस्या — छवि स्पष्ट नहीं है।',
    errorMismatchReport: 'यह एक लैब रिपोर्ट / टेस्ट जैसा दिखता है।',
    errorMismatchMedicine: 'यह एक दवा पैक / स्ट्रिप जैसा दिखता है।',
    errorChat: 'प्रश्न को संसाधित नहीं किया जा सका।',
    chatTitle: 'आपके प्रश्न',
    chatPlaceholderMedicine: 'इस दवा के बारे में पूछें...',
    chatPlaceholderReport: 'इस रिपोर्ट के बारे में पूछें...',
    retryNew: 'नई छवि अपलोड करें',
    retrySame: '同じ画像で再試行',
    typeMedicine: 'दवा',
    typeReport: 'लैब रिपोर्ट',
    typePrescription: 'पर्चे',
    typeOther: 'अन्य',
    match: '% मिलान',
    aboutMedicine: 'इस दवा के बारे में',
    aboutReport: 'रिपोर्ट का सरल अर्थ',
    formulaTitle: 'सूत्र और यह कैसे काम करता है',
    formulaLabel: 'सूत्र / लवण',
    howItWorks: 'यह शरीर में कैसे काम करता है',
    whyInMedicine: 'यह इस दवा में क्यों उपयोग किया जाता है',
    howToUse: 'कैसे उपयोग करें',
    priceApprox: 'अनुमानित मूल्य: Rs.',
    altIntro: 'समान / समान सूत्र — अन्य कंपनियाँ (अनुमानित)',
    alternatives: 'वैकल्पिक दवाएँ',
    onPackageMedicine: 'पैकेजिंग पर लिखा',
    onPackageReport: 'रिपोर्ट पर लिखा',
    notesMedicine: 'महत्वपूर्ण नोट्स',
    notesReport: 'महत्वपूर्ण बिंदु',
  },
  history: {
    tabs: {
      history: 'इतिहास',
    },
    emptyTitle: 'अभी तक कोई स्कैन नहीं',
    emptySub: 'एक दवा या रिपोर्ट स्कैन करें — यह यहाँ संग्रहीत हो जाएगा',
    deleteTitle: 'स्कैन हटाएँ?',
    deleteMessage: '{name}',
    confirmText: 'हटाएँ',
    cancelText: 'रद्द करें',
    typeReport: 'लैब रिपोर्ट',
    typePrescription: 'पर्चे',
    typeMedicine: 'दवा',
    typeOther: 'अन्य',
    scan: 'स्कैन',
  },
};