export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'ur', label: 'Urdu', native: 'اردو', flag: '🇵🇰' },
  { code: 'ar', label: 'Arabic', native: 'العربية', flag: '🇸🇦' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ps', label: 'Pashto', native: 'پښتو', flag: '🇦🇫' },
  { code: 'pa', label: 'Punjabi', native: 'پنجابی', flag: '🇵🇰' },
  { code: 'sd', label: 'Sindhi', native: 'سنڌي', flag: '🇵🇰' },
  { code: 'fa', label: 'Persian', native: 'فارسی', flag: '🇮🇷' },
  { code: 'tr', label: 'Turkish', native: 'Türkçe', flag: '🇹🇷' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা', flag: '🇧🇩' },
  { code: 'zh', label: 'Chinese', native: '中文', flag: '🇨🇳' },
  { code: 'es', label: 'Spanish', native: 'Español', flag: '🇪🇸' },
  { code: 'fr', label: 'French', native: 'Français', flag: '🇫🇷' },
  { code: 'de', label: 'German', native: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt', label: 'Portuguese', native: 'Português', flag: '🇵🇹' },
  { code: 'ru', label: 'Russian', native: 'Русский', flag: '🇷🇺' },
  { code: 'id', label: 'Indonesian', native: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ja', label: 'Japanese', native: '日本語', flag: '🇯🇵' },
  { code: 'ko', label: 'Korean', native: '한국어', flag: '🇰🇷' },
  { code: 'th', label: 'Thai', native: 'ไทย', flag: '🇹🇭' },
];

export const LANGUAGES = SUPPORTED_LANGUAGES;

const en = {
  common: {
    continue: 'Continue',
    cancel: 'Cancel',
    skip: 'Skip',
    retry: 'Retry',
    loading: 'Loading…',
    consultDoctor:
      'This is not a medical diagnosis. Always consult a licensed doctor or pharmacist before making health decisions.',
  },
  splash: { tagline: 'Understand your medicines & reports instantly' },
  auth: {
    title: 'Welcome to MedScan',
    subtitle: 'Scan medicines and lab reports to get clear, simple explanations.',
    phone: 'Continue with Phone',
    google: 'Continue with Google',
    email: 'Continue with Email',
    terms: 'By continuing, you agree to our Terms of Service and Privacy Policy.',
  },
  home: {
    greeting: 'Hello',
    scanCta: 'Scan Now',
    scanSubtitle: 'Medicine or Lab Report',
    quickTips: 'Quick Tips',
    recentScan: 'Recent Scan',
    viewAll: 'View all',
    noRecentScan: 'No scans yet',
    noRecentScanSubtitle: 'Your most recent scan will appear here.',
    scansLeft: 'scans left today',
    upgrade: 'Premium coming soon',
    tip1: 'Keep the label flat and well-lit for the clearest scan.',
    tip2: 'For reports, scan one page at a time in order.',
    tip3: 'MedScan explains reports — it never replaces your doctor.',
  },
  tabs: { home: 'Home', scan: 'Scan', history: 'History', profile: 'Profile' },
  profile: {
    title: 'My',
    subtitle: 'Profile',
    signedIn: 'Signed in',
    guest: 'Guest mode',
    totalScans: 'Total Scans',
    language: 'Language',
    settings: 'Settings',
    notifications: 'Notifications',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    rate: 'Rate App',
    support: 'Support',
    logout: 'Log Out',
    logoutConfirm: 'Log out?',
    logoutMsg: 'You will be signed out of your account.',
    cancel: 'Cancel',
    selectLanguage: 'Select Language',
  },
};

const ur = {
  common: {
    continue: 'جاری رکھیں',
    cancel: 'منسوخ کریں',
    skip: 'نظر انداز کریں',
    retry: 'دوبارہ کوشش کریں',
    loading: 'لوڈ ہو رہا ہے…',
    consultDoctor:
      'یہ طبی تشخیص نہیں ہے۔ صحت کا فیصلہ کرنے سے پہلے ڈاکٹر یا فارماسسٹ سے مشورہ کریں۔',
  },
  splash: { tagline: 'اپنی دوائیوں اور رپورٹس کو فوری طور پر سمجھیں' },
  auth: {
    title: 'میڈ اسکین میں خوش آمدید',
    subtitle: 'دوائیوں اور لیب رپورٹس اسکین کریں اور آسان وضاحت حاصل کریں۔',
    phone: 'فون سے جاری رکھیں',
    google: 'گوگل سے جاری رکھیں',
    email: 'ای میل سے جاری رکھیں',
    terms: 'جاری رکھ کر آپ ہماری شرائط اور پرائیویسی سے اتفاق کرتے ہیں۔',
  },
  home: {
    greeting: 'ہیلو',
    scanCta: 'ابھی اسکین کریں',
    scanSubtitle: 'دوائی یا لیب رپورٹ',
    quickTips: 'مفید تجاویز',
    recentScan: 'حالیہ اسکین',
    viewAll: 'سب دیکھیں',
    noRecentScan: 'ابھی کوئی اسکین نہیں',
    noRecentScanSubtitle: 'آپ کا حالیہ اسکین یہاں نظر آئے گا۔',
    scansLeft: 'آج باقی اسکینز',
    upgrade: 'پریمیم جلد آ رہا ہے',
    tip1: 'لیبل کو سیدھا اور روشن جگہ رکھیں۔',
    tip2: 'رپورٹ ایک صفحہ ایک وقت اسکین کریں۔',
    tip3: 'میڈ اسکین وضاحت دیتا ہے — ڈاکٹر کا متبادل نہیں۔',
  },
  tabs: { home: 'ہوم', scan: 'اسکین', history: 'تاریخ', profile: 'پروفائل' },
  profile: {
    title: 'میرا',
    subtitle: 'پروفائل',
    signedIn: 'سائن ان',
    guest: 'مہمان موڈ',
    totalScans: 'کل اسکینز',
    language: 'زبان',
    settings: 'ترتیبات',
    notifications: 'نوٹیفیکیشنز',
    privacy: 'پرائیویسی پالیسی',
    terms: 'شرائطِ خدمت',
    rate: 'ایپ ریٹ کریں',
    support: 'سپورٹ',
    logout: 'لاگ آؤٹ',
    logoutConfirm: 'لاگ آؤٹ؟',
    logoutMsg: 'آپ اکاؤنٹ سے نکل جائیں گے۔',
    cancel: 'منسوخ',
    selectLanguage: 'زبان منتخب کریں',
  },
};

const ar = {
  common: {
    continue: 'متابعة',
    cancel: 'إلغاء',
    skip: 'تخطي',
    retry: 'إعادة المحاولة',
    loading: 'جاري التحميل…',
    consultDoctor: 'هذا ليس تشخيصاً طبياً. استشر طبيباً أو صيدلياً قبل أي قرار صحي.',
  },
  splash: { tagline: 'افهم أدويتك وتقاريرك فوراً' },
  auth: {
    title: 'مرحباً بك في MedScan',
    subtitle: 'امسح الأدوية وتقارير المختبر واحصل على شرح بسيط.',
    phone: 'المتابعة بالهاتف',
    google: 'المتابعة مع Google',
    email: 'المتابعة بالبريد',
    terms: 'بالمتابعة فإنك توافق على الشروط وسياسة الخصوصية.',
  },
  home: {
    greeting: 'مرحباً',
    scanCta: 'امسح الآن',
    scanSubtitle: 'دواء أو تقرير مختبر',
    quickTips: 'نصائح سريعة',
    recentScan: 'آخر مسح',
    viewAll: 'عرض الكل',
    noRecentScan: 'لا عمليات مسح بعد',
    noRecentScanSubtitle: 'سيظهر آخر مسح هنا.',
    scansLeft: 'عمليات مسح متبقية اليوم',
    upgrade: 'قريباً النسخة المميزة',
    tip1: 'اجعل الملصق مستوياً ومضاء جيداً.',
    tip2: 'للتقرير امسح صفحة واحدة في كل مرة.',
    tip3: 'MedScan يشرح فقط — لا يغني عن الطبيب.',
  },
  tabs: { home: 'الرئيسية', scan: 'مسح', history: 'السجل', profile: 'الملف' },
  profile: {
    title: 'ملفي',
    subtitle: 'الشخصي',
    signedIn: 'مسجل الدخول',
    guest: 'وضع الضيف',
    totalScans: 'إجمالي المسح',
    language: 'اللغة',
    settings: 'الإعدادات',
    notifications: 'الإشعارات',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الخدمة',
    rate: 'قيّم التطبيق',
    support: 'الدعم',
    logout: 'تسجيل الخروج',
    logoutConfirm: 'تسجيل الخروج؟',
    logoutMsg: 'سيتم تسجيل خروجك من الحساب.',
    cancel: 'إلغاء',
    selectLanguage: 'اختر اللغة',
  },
};

const hi = {
  common: {
    continue: 'जारी रखें',
    cancel: 'रद्द करें',
    skip: 'छोड़ें',
    retry: 'फिर कोशिश करें',
    loading: 'लोड हो रहा है…',
    consultDoctor: 'यह चिकित्सा निदान नहीं है। कोई भी स्वास्थ्य निर्णय लेने से पहले डॉक्टर से सलाह लें।',
  },
  splash: { tagline: 'अपनी दवाइयाँ और रिपोर्ट तुरंत समझें' },
  auth: {
    title: 'MedScan में आपका स्वागत है',
    subtitle: 'दवा और लैब रिपोर्ट स्कैन करें और सरल व्याख्या पाएं।',
    phone: 'फ़ोन से जारी रखें',
    google: 'Google से जारी रखें',
    email: 'ईमेल से जारी रखें',
    terms: 'जारी रखकर आप हमारी शर्तों और गोपनीयता से सहमत हैं।',
  },
  home: {
    greeting: 'नमस्ते',
    scanCta: 'अभी स्कैन करें',
    scanSubtitle: 'दवा या लैब रिपोर्ट',
    quickTips: 'त्वरित सुझाव',
    recentScan: 'हालिया स्कैन',
    viewAll: 'सभी देखें',
    noRecentScan: 'अभी कोई स्कैन नहीं',
    noRecentScanSubtitle: 'आपका हालिया स्कैन यहाँ दिखेगा।',
    scansLeft: 'आज बचे स्कैन',
    upgrade: 'प्रीमियम जल्द आ रहा है',
    tip1: 'लेबल को सीधा और अच्छी रोशनी में रखें।',
    tip2: 'रिपोर्ट एक पेज एक बार स्कैन करें।',
    tip3: 'MedScan केवल समझाता है — डॉक्टर का विकल्प नहीं।',
  },
  tabs: { home: 'होम', scan: 'स्कैन', history: 'इतिहास', profile: 'प्रोफ़ाइल' },
  profile: {
    title: 'मेरी',
    subtitle: 'प्रोफ़ाइल',
    signedIn: 'साइन इन',
    guest: 'अतिथि मोड',
    totalScans: 'कुल स्कैन',
    language: 'भाषा',
    settings: 'सेटिंग्स',
    notifications: 'सूचनाएं',
    privacy: 'गोपनीयता नीति',
    terms: 'सेवा की शर्तें',
    rate: 'ऐप रेट करें',
    support: 'सहायता',
    logout: 'लॉग आउट',
    logoutConfirm: 'लॉग आउट?',
    logoutMsg: 'आप खाते से बाहर हो जाएंगे।',
    cancel: 'रद्द',
    selectLanguage: 'भाषा चुनें',
  },
};

const ps = {
  common: {
    continue: 'ادامه',
    cancel: 'لغوه',
    skip: 'تیریدل',
    retry: 'بیا هڅه',
    loading: 'بارېږي…',
    consultDoctor: 'دا طبي تشخیص نه دی. د روغتیا پریکړې دمخه ډاکټر سره مشوره وکړئ.',
  },
  splash: { tagline: 'خپلې درمل او راپورونه سمدستي وپوهېږئ' },
  auth: {
    title: 'MedScan ته ښه راغلاست',
    subtitle: 'درمل او لابراتوار راپورونه سکین کړئ او ساده تشریح ترلاسه کړئ.',
    phone: 'د تلیفون سره ادامه',
    google: 'د Google سره ادامه',
    email: 'د بریښنالیک سره ادامه',
    terms: 'ادامه ورکولو سره تاسو زموږ شرایط منئ.',
  },
  home: {
    greeting: 'سلام',
    scanCta: 'اوس سکین کړئ',
    scanSubtitle: 'درمل یا لابراتوار راپور',
    quickTips: 'ګړندي مشورې',
    recentScan: 'وروستی سکین',
    viewAll: 'ټول وګورئ',
    noRecentScan: 'تر اوسه سکین نشته',
    noRecentScanSubtitle: 'ستاسو وروستی سکین دلته ښکاره کېږي.',
    scansLeft: 'نن پاتې سکینونه',
    upgrade: 'پریمیم ژر راځي',
    tip1: 'لیبل مستقیم او روښانه وساتئ.',
    tip2: 'راپور یو پاڼه په یو وخت سکین کړئ.',
    tip3: 'MedScan یوازې تشریح کوي — ډاکټر نه بدلوي.',
  },
  tabs: { home: 'کور', scan: 'سکین', history: 'تاریخ', profile: 'پروفایل' },
  profile: {
    title: 'زما',
    subtitle: 'پروفایل',
    signedIn: 'ننوتی',
    guest: 'میلمه حالت',
    totalScans: 'ټول سکینونه',
    language: 'ژبه',
    settings: 'تنظیمات',
    notifications: 'خبرتیاوې',
    privacy: 'د محرمیت تګلاره',
    terms: 'د خدمت شرایط',
    rate: 'اپلیکیشن درجه کړئ',
    support: 'ملاتړ',
    logout: 'وتل',
    logoutConfirm: 'وتل؟',
    logoutMsg: 'تاسو به له حساب څخه ووځئ.',
    cancel: 'لغوه',
    selectLanguage: 'ژبه وټاکئ',
  },
};

const pa = {
  common: {
    continue: 'جاری رکھو',
    cancel: 'رد کرو',
    skip: 'چھوڑو',
    retry: 'دوبارہ کوشش',
    loading: 'لوڈ ہو رہا ہے…',
    consultDoctor: 'ایہ طبی تشخیص نہیں۔ صحت دے فیصلے توں پہلاں ڈاکٹر نال صلاح کرو۔',
  },
  splash: { tagline: 'اپنیاں دوائیاں تے رپورٹاں فوری سمجھو' },
  auth: {
    title: 'MedScan وچ خوش آمدید',
    subtitle: 'دوا تے لیب رپورٹ سکین کرو تے سادہ وضاحت حاصل کرو۔',
    phone: 'فون نال جاری',
    google: 'Google نال جاری',
    email: 'ای میل نال جاری',
    terms: 'جاری رکھ کے تسی ساڈیاں شرطاں نال متفق او۔',
  },
  home: {
    greeting: 'ہیلو',
    scanCta: 'ہن سکین کرو',
    scanSubtitle: 'دوا یا لیب رپورٹ',
    quickTips: 'فوری مشورے',
    recentScan: 'حالیہ سکین',
    viewAll: 'سارے ویکھو',
    noRecentScan: 'ہلے کوئی سکین نہیں',
    noRecentScanSubtitle: 'تہاڈا حالیہ سکین ایتھے نظر آئے گا۔',
    scansLeft: 'اج باقی سکین',
    upgrade: 'پریمیم جلد آ رہیا اے',
    tip1: 'لیبل سیدھا تے روشنی وچ رکھو۔',
    tip2: 'رپورٹ اک صفحہ اک واری سکین کرو۔',
    tip3: 'MedScan صرف وضاحت دیندا اے — ڈاکٹر دا متبادل نہیں۔',
  },
  tabs: { home: 'ہوم', scan: 'سکین', history: 'تاریخ', profile: 'پروفائل' },
  profile: {
    title: 'میرا',
    subtitle: 'پروفائل',
    signedIn: 'سائن ان',
    guest: 'مہمان موڈ',
    totalScans: 'کل سکین',
    language: 'زبان',
    settings: 'ترتیبات',
    notifications: 'نوٹیفیکیشنز',
    privacy: 'پرائیویسی',
    terms: 'شرائط',
    rate: 'ایپ ریٹ کرو',
    support: 'سپورٹ',
    logout: 'لاگ آؤٹ',
    logoutConfirm: 'لاگ آؤٹ؟',
    logoutMsg: 'تسی اکاؤنٹ توں نکل جاؤ گے۔',
    cancel: 'رد',
    selectLanguage: 'زبان چنو',
  },
};

const sd = {
  common: {
    continue: 'جاري رکو',
    cancel: 'منسوخ',
    skip: 'ڇڏيو',
    retry: 'ٻيهر ڪوشش',
    loading: 'لوڊ ٿي رهيو آهي…',
    consultDoctor: 'هي طبي تشخيص نه آهي. صحت جو فيصلو ڪرڻ کان اڳ ڊاڪٽر سان صلاح ڪريو.',
  },
  splash: { tagline: 'پنهنجون دوائون ۽ رپورٽون فوري سمجهو' },
  auth: {
    title: 'MedScan ۾ ڀليڪار',
    subtitle: 'دوا ۽ ليبارٽري رپورٽ اسڪين ڪريو ۽ سادي وضاحت حاصل ڪريو.',
    phone: 'فون سان جاري',
    google: 'Google سان جاري',
    email: 'اي ميل سان جاري',
    terms: 'جاري رکي توهان اسان جي شرطن سان متفق آهيو.',
  },
  home: {
    greeting: 'هيلو',
    scanCta: 'هاڻي اسڪين ڪريو',
    scanSubtitle: 'دوا يا ليبارٽري رپورٽ',
    quickTips: 'جلدي صلاحون',
    recentScan: 'تازو اسڪين',
    viewAll: 'سڀ ڏسو',
    noRecentScan: 'اڃا ڪو اسڪين ناهي',
    noRecentScanSubtitle: 'توهان جو تازو اسڪين هتي نظر ايندو.',
    scansLeft: 'اڄ باقي اسڪين',
    upgrade: 'پريميم جلد ايندو',
    tip1: 'ليبل سڌو ۽ روشن جاءِ تي رکو.',
    tip2: 'رپورٽ هڪ صفحو هڪ وقت اسڪين ڪريو.',
    tip3: 'MedScan صرف وضاحت ڏئي ٿو — ڊاڪٽر جو متبادل نه.',
  },
  tabs: { home: 'گهر', scan: 'اسڪين', history: 'تاريخ', profile: 'پروفائل' },
  profile: {
    title: 'منهنجو',
    subtitle: 'پروفائل',
    signedIn: 'سائن ان',
    guest: 'مهمان موڊ',
    totalScans: 'ڪل اسڪين',
    language: 'ٻولي',
    settings: 'سيٽنگون',
    notifications: 'اطلاع',
    privacy: 'رازداري',
    terms: 'شرطون',
    rate: 'ايپ ريٽ ڪريو',
    support: 'مدد',
    logout: 'لاگ آئوٽ',
    logoutConfirm: 'لاگ آئوٽ؟',
    logoutMsg: 'توهان اڪائونٽ مان نڪري ويندا.',
    cancel: 'منسوخ',
    selectLanguage: 'ٻولي چونڊيو',
  },
};

const fa = {
  common: {
    continue: 'ادامه',
    cancel: 'لغو',
    skip: 'رد شدن',
    retry: 'تلاش دوباره',
    loading: 'در حال بارگذاری…',
    consultDoctor: 'این تشخیص پزشکی نیست. قبل از هر تصمیم با پزشک مشورت کنید.',
  },
  splash: { tagline: 'داروها و گزارش‌های خود را فوراً بفهمید' },
  auth: {
    title: 'به MedScan خوش آمدید',
    subtitle: 'دارو و گزارش آزمایشگاه را اسکن کنید و توضیح ساده بگیرید.',
    phone: 'ادامه با تلفن',
    google: 'ادامه با Google',
    email: 'ادامه با ایمیل',
    terms: 'با ادامه، شرایط و حریم خصوصی را می‌پذیرید.',
  },
  home: {
    greeting: 'سلام',
    scanCta: 'همین حالا اسکن کنید',
    scanSubtitle: 'دارو یا گزارش آزمایشگاه',
    quickTips: 'نکات سریع',
    recentScan: 'آخرین اسکن',
    viewAll: 'مشاهده همه',
    noRecentScan: 'هنوز اسکنی نیست',
    noRecentScanSubtitle: 'آخرین اسکن شما اینجا نشان داده می‌شود.',
    scansLeft: 'اسکن باقی‌مانده امروز',
    upgrade: 'پریمیوم به زودی',
    tip1: 'برچسب را صاف و روشن نگه دارید.',
    tip2: 'گزارش را صفحه به صفحه اسکن کنید.',
    tip3: 'MedScan فقط توضیح می‌دهد — جایگزین پزشک نیست.',
  },
  tabs: { home: 'خانه', scan: 'اسکن', history: 'تاریخچه', profile: 'پروفایل' },
  profile: {
    title: 'پروفایل',
    subtitle: 'من',
    signedIn: 'وارد شده',
    guest: 'حالت مهمان',
    totalScans: 'کل اسکن‌ها',
    language: 'زبان',
    settings: 'تنظیمات',
    notifications: 'اعلان‌ها',
    privacy: 'حریم خصوصی',
    terms: 'شرایط خدمات',
    rate: 'امتیاز به برنامه',
    support: 'پشتیبانی',
    logout: 'خروج',
    logoutConfirm: 'خروج؟',
    logoutMsg: 'از حساب خارج می‌شوید.',
    cancel: 'لغو',
    selectLanguage: 'انتخاب زبان',
  },
};

const tr = {
  common: {
    continue: 'Devam',
    cancel: 'İptal',
    skip: 'Atla',
    retry: 'Tekrar dene',
    loading: 'Yükleniyor…',
    consultDoctor: 'Bu tıbbi teşhis değildir. Sağlık kararı öncesi doktora danışın.',
  },
  splash: { tagline: 'İlaçlarınızı ve raporlarınızı anında anlayın' },
  auth: {
    title: "MedScan'e hoş geldiniz",
    subtitle: 'İlaç ve laboratuvar raporlarını tarayın, basit açıklama alın.',
    phone: 'Telefon ile devam',
    google: 'Google ile devam',
    email: 'E-posta ile devam',
    terms: 'Devam ederek şartları ve gizliliği kabul etmiş olursunuz.',
  },
  home: {
    greeting: 'Merhaba',
    scanCta: 'Şimdi tara',
    scanSubtitle: 'İlaç veya laboratuvar raporu',
    quickTips: 'Hızlı ipuçları',
    recentScan: 'Son tarama',
    viewAll: 'Tümünü gör',
    noRecentScan: 'Henüz tarama yok',
    noRecentScanSubtitle: 'Son taramanız burada görünecek.',
    scansLeft: 'bugün kalan tarama',
    upgrade: 'Premium yakında',
    tip1: 'Etiketi düz ve aydınlık tutun.',
    tip2: 'Raporu sayfa sayfa tarayın.',
    tip3: 'MedScan yalnızca açıklar — doktorun yerini tutmaz.',
  },
  tabs: { home: 'Ana sayfa', scan: 'Tara', history: 'Geçmiş', profile: 'Profil' },
  profile: {
    title: 'Profilim',
    subtitle: '',
    signedIn: 'Giriş yapıldı',
    guest: 'Misafir modu',
    totalScans: 'Toplam tarama',
    language: 'Dil',
    settings: 'Ayarlar',
    notifications: 'Bildirimler',
    privacy: 'Gizlilik politikası',
    terms: 'Hizmet şartları',
    rate: 'Uygulamayı değerlendir',
    support: 'Destek',
    logout: 'Çıkış yap',
    logoutConfirm: 'Çıkış yapılsın mı?',
    logoutMsg: 'Hesabınızdan çıkış yapılacak.',
    cancel: 'İptal',
    selectLanguage: 'Dil seçin',
  },
};

const bn = {
  common: {
    continue: 'চালিয়ে যান',
    cancel: 'বাতিল',
    skip: 'এড়িয়ে যান',
    retry: 'আবার চেষ্টা',
    loading: 'লোড হচ্ছে…',
    consultDoctor: 'এটি চিকিৎসা নির্ণয় নয়। স্বাস্থ্য সিদ্ধান্তের আগে ডাক্তারের পরামর্শ নিন।',
  },
  splash: { tagline: 'আপনার ওষুধ ও রিপোর্ট তাৎক্ষণিক বুঝুন' },
  auth: {
    title: 'MedScan-এ স্বাগতম',
    subtitle: 'ওষুধ ও ল্যাব রিপোর্ট স্ক্যান করুন এবং সহজ ব্যাখ্যা পান।',
    phone: 'ফোন দিয়ে চালিয়ে যান',
    google: 'Google দিয়ে চালিয়ে যান',
    email: 'ইমেইল দিয়ে চালিয়ে যান',
    terms: 'চালিয়ে গেলে আপনি শর্তাবলীতে সম্মত।',
  },
  home: {
    greeting: 'হ্যালো',
    scanCta: 'এখনই স্ক্যান করুন',
    scanSubtitle: 'ওষুধ বা ল্যাব রিপোর্ট',
    quickTips: 'দ্রুত টিপস',
    recentScan: 'সাম্প্রতিক স্ক্যান',
    viewAll: 'সব দেখুন',
    noRecentScan: 'এখনো কোনো স্ক্যান নেই',
    noRecentScanSubtitle: 'আপনার সাম্প্রতিক স্ক্যান এখানে দেখাবে।',
    scansLeft: 'আজ বাকি স্ক্যান',
    upgrade: 'প্রিমিয়াম শীঘ্রই আসছে',
    tip1: 'লেবেল সোজা ও ভালো আলোতে রাখুন।',
    tip2: 'রিপোর্ট এক পৃষ্ঠা করে স্ক্যান করুন।',
    tip3: 'MedScan শুধু ব্যাখ্যা করে — ডাক্তারের বিকল্প নয়।',
  },
  tabs: { home: 'হোম', scan: 'স্ক্যান', history: 'ইতিহাস', profile: 'প্রোফাইল' },
  profile: {
    title: 'আমার',
    subtitle: 'প্রোফাইল',
    signedIn: 'সাইন ইন',
    guest: 'অতিথি মোড',
    totalScans: 'মোট স্ক্যান',
    language: 'ভাষা',
    settings: 'সেটিংস',
    notifications: 'বিজ্ঞপ্তি',
    privacy: 'গোপনীয়তা নীতি',
    terms: 'সেবার শর্ত',
    rate: 'অ্যাপ রেট করুন',
    support: 'সহায়তা',
    logout: 'লগ আউট',
    logoutConfirm: 'লগ আউট?',
    logoutMsg: 'আপনি অ্যাকাউন্ট থেকে বের হয়ে যাবেন।',
    cancel: 'বাতিল',
    selectLanguage: 'ভাষা নির্বাচন করুন',
  },
};

const zh = {
  common: {
    continue: '继续',
    cancel: '取消',
    skip: '跳过',
    retry: '重试',
    loading: '加载中…',
    consultDoctor: '这不是医疗诊断。做出健康决定前请咨询医生或药师。',
  },
  splash: { tagline: '立即了解您的药品与报告' },
  auth: {
    title: '欢迎使用 MedScan',
    subtitle: '扫描药品和化验报告，获得简单说明。',
    phone: '使用手机继续',
    google: '使用 Google 继续',
    email: '使用邮箱继续',
    terms: '继续即表示您同意服务条款和隐私政策。',
  },
  home: {
    greeting: '你好',
    scanCta: '立即扫描',
    scanSubtitle: '药品或化验报告',
    quickTips: '快速提示',
    recentScan: '最近扫描',
    viewAll: '查看全部',
    noRecentScan: '暂无扫描',
    noRecentScanSubtitle: '您最近的扫描将显示在这里。',
    scansLeft: '今日剩余扫描',
    upgrade: '高级版即将推出',
    tip1: '保持标签平整并光线充足。',
    tip2: '报告请按页依次扫描。',
    tip3: 'MedScan 仅作说明 — 不能替代医生。',
  },
  tabs: { home: '首页', scan: '扫描', history: '历史', profile: '我的' },
  profile: {
    title: '我的',
    subtitle: '资料',
    signedIn: '已登录',
    guest: '访客模式',
    totalScans: '总扫描数',
    language: '语言',
    settings: '设置',
    notifications: '通知',
    privacy: '隐私政策',
    terms: '服务条款',
    rate: '评价应用',
    support: '支持',
    logout: '退出登录',
    logoutConfirm: '退出登录？',
    logoutMsg: '您将退出当前账户。',
    cancel: '取消',
    selectLanguage: '选择语言',
  },
};

const es = {
  common: {
    continue: 'Continuar',
    cancel: 'Cancelar',
    skip: 'Omitir',
    retry: 'Reintentar',
    loading: 'Cargando…',
    consultDoctor: 'Esto no es un diagnóstico médico. Consulte a un médico antes de decidir.',
  },
  splash: { tagline: 'Entiende tus medicinas e informes al instante' },
  auth: {
    title: 'Bienvenido a MedScan',
    subtitle: 'Escanea medicinas e informes de laboratorio y obtén explicaciones claras.',
    phone: 'Continuar con teléfono',
    google: 'Continuar con Google',
    email: 'Continuar con correo',
    terms: 'Al continuar, aceptas los Términos y la Política de privacidad.',
  },
  home: {
    greeting: 'Hola',
    scanCta: 'Escanear ahora',
    scanSubtitle: 'Medicina o informe de laboratorio',
    quickTips: 'Consejos rápidos',
    recentScan: 'Escaneo reciente',
    viewAll: 'Ver todo',
    noRecentScan: 'Aún no hay escaneos',
    noRecentScanSubtitle: 'Tu escaneo más reciente aparecerá aquí.',
    scansLeft: 'escaneos restantes hoy',
    upgrade: 'Premium pronto',
    tip1: 'Mantén la etiqueta plana y bien iluminada.',
    tip2: 'Para informes, escanea una página a la vez.',
    tip3: 'MedScan solo explica — no sustituye al médico.',
  },
  tabs: { home: 'Inicio', scan: 'Escanear', history: 'Historial', profile: 'Perfil' },
  profile: {
    title: 'Mi',
    subtitle: 'Perfil',
    signedIn: 'Conectado',
    guest: 'Modo invitado',
    totalScans: 'Escaneos totales',
    language: 'Idioma',
    settings: 'Ajustes',
    notifications: 'Notificaciones',
    privacy: 'Política de privacidad',
    terms: 'Términos del servicio',
    rate: 'Valorar la app',
    support: 'Soporte',
    logout: 'Cerrar sesión',
    logoutConfirm: '¿Cerrar sesión?',
    logoutMsg: 'Se cerrará tu sesión.',
    cancel: 'Cancelar',
    selectLanguage: 'Seleccionar idioma',
  },
};

const fr = {
  common: {
    continue: 'Continuer',
    cancel: 'Annuler',
    skip: 'Passer',
    retry: 'Réessayer',
    loading: 'Chargement…',
    consultDoctor: "Ce n'est pas un diagnostic médical. Consultez un médecin avant toute décision.",
  },
  splash: { tagline: 'Comprenez vos médicaments et rapports instantanément' },
  auth: {
    title: 'Bienvenue sur MedScan',
    subtitle: 'Scannez médicaments et rapports de labo pour des explications simples.',
    phone: 'Continuer avec le téléphone',
    google: 'Continuer avec Google',
    email: "Continuer avec l'e-mail",
    terms: 'En continuant, vous acceptez les Conditions et la Confidentialité.',
  },
  home: {
    greeting: 'Bonjour',
    scanCta: 'Scanner maintenant',
    scanSubtitle: 'Médicament ou rapport de labo',
    quickTips: 'Astuces rapides',
    recentScan: 'Scan récent',
    viewAll: 'Tout voir',
    noRecentScan: 'Aucun scan pour le moment',
    noRecentScanSubtitle: 'Votre dernier scan apparaîtra ici.',
    scansLeft: 'scans restants aujourd’hui',
    upgrade: 'Premium bientôt',
    tip1: "Gardez l'étiquette plate et bien éclairée.",
    tip2: 'Pour les rapports, scannez une page à la fois.',
    tip3: 'MedScan explique seulement — ne remplace pas le médecin.',
  },
  tabs: { home: 'Accueil', scan: 'Scanner', history: 'Historique', profile: 'Profil' },
  profile: {
    title: 'Mon',
    subtitle: 'Profil',
    signedIn: 'Connecté',
    guest: 'Mode invité',
    totalScans: 'Scans totaux',
    language: 'Langue',
    settings: 'Paramètres',
    notifications: 'Notifications',
    privacy: 'Politique de confidentialité',
    terms: "Conditions d'utilisation",
    rate: "Noter l'appli",
    support: 'Support',
    logout: 'Déconnexion',
    logoutConfirm: 'Se déconnecter ?',
    logoutMsg: 'Vous serez déconnecté du compte.',
    cancel: 'Annuler',
    selectLanguage: 'Choisir la langue',
  },
};

const de = {
  common: {
    continue: 'Weiter',
    cancel: 'Abbrechen',
    skip: 'Überspringen',
    retry: 'Erneut versuchen',
    loading: 'Laden…',
    consultDoctor: 'Dies ist keine medizinische Diagnose. Fragen Sie vor Entscheidungen einen Arzt.',
  },
  splash: { tagline: 'Verstehen Sie Medikamente & Berichte sofort' },
  auth: {
    title: 'Willkommen bei MedScan',
    subtitle: 'Scannen Sie Medikamente und Laborberichte für einfache Erklärungen.',
    phone: 'Mit Telefon fortfahren',
    google: 'Mit Google fortfahren',
    email: 'Mit E-Mail fortfahren',
    terms: 'Mit dem Fortfahren akzeptieren Sie die AGB und Datenschutz.',
  },
  home: {
    greeting: 'Hallo',
    scanCta: 'Jetzt scannen',
    scanSubtitle: 'Medikament oder Laborbericht',
    quickTips: 'Schnelltipps',
    recentScan: 'Letzter Scan',
    viewAll: 'Alle anzeigen',
    noRecentScan: 'Noch keine Scans',
    noRecentScanSubtitle: 'Ihr letzter Scan erscheint hier.',
    scansLeft: 'Scans heute übrig',
    upgrade: 'Premium kommt bald',
    tip1: 'Etikett flach und gut beleuchtet halten.',
    tip2: 'Berichte seitenweise scannen.',
    tip3: 'MedScan erklärt nur — ersetzt keinen Arzt.',
  },
  tabs: { home: 'Start', scan: 'Scannen', history: 'Verlauf', profile: 'Profil' },
  profile: {
    title: 'Mein',
    subtitle: 'Profil',
    signedIn: 'Angemeldet',
    guest: 'Gastmodus',
    totalScans: 'Scans gesamt',
    language: 'Sprache',
    settings: 'Einstellungen',
    notifications: 'Benachrichtigungen',
    privacy: 'Datenschutz',
    terms: 'Nutzungsbedingungen',
    rate: 'App bewerten',
    support: 'Support',
    logout: 'Abmelden',
    logoutConfirm: 'Abmelden?',
    logoutMsg: 'Sie werden abgemeldet.',
    cancel: 'Abbrechen',
    selectLanguage: 'Sprache wählen',
  },
};

const pt = {
  common: {
    continue: 'Continuar',
    cancel: 'Cancelar',
    skip: 'Pular',
    retry: 'Tentar de novo',
    loading: 'Carregando…',
    consultDoctor: 'Isto não é um diagnóstico médico. Consulte um médico antes de decidir.',
  },
  splash: { tagline: 'Entenda seus remédios e laudos na hora' },
  auth: {
    title: 'Bem-vindo ao MedScan',
    subtitle: 'Escaneie remédios e laudos e receba explicações simples.',
    phone: 'Continuar com telefone',
    google: 'Continuar com Google',
    email: 'Continuar com e-mail',
    terms: 'Ao continuar, você aceita os Termos e a Privacidade.',
  },
  home: {
    greeting: 'Olá',
    scanCta: 'Escanear agora',
    scanSubtitle: 'Remédio ou laudo laboratorial',
    quickTips: 'Dicas rápidas',
    recentScan: 'Scan recente',
    viewAll: 'Ver tudo',
    noRecentScan: 'Nenhum scan ainda',
    noRecentScanSubtitle: 'Seu scan mais recente aparecerá aqui.',
    scansLeft: 'scans restantes hoje',
    upgrade: 'Premium em breve',
    tip1: 'Mantenha o rótulo plano e bem iluminado.',
    tip2: 'Para laudos, escaneie uma página por vez.',
    tip3: 'MedScan só explica — não substitui o médico.',
  },
  tabs: { home: 'Início', scan: 'Escanear', history: 'Histórico', profile: 'Perfil' },
  profile: {
    title: 'Meu',
    subtitle: 'Perfil',
    signedIn: 'Conectado',
    guest: 'Modo convidado',
    totalScans: 'Total de scans',
    language: 'Idioma',
    settings: 'Configurações',
    notifications: 'Notificações',
    privacy: 'Política de privacidade',
    terms: 'Termos de serviço',
    rate: 'Avaliar o app',
    support: 'Suporte',
    logout: 'Sair',
    logoutConfirm: 'Sair?',
    logoutMsg: 'Você será desconectado da conta.',
    cancel: 'Cancelar',
    selectLanguage: 'Selecionar idioma',
  },
};

const ru = {
  common: {
    continue: 'Продолжить',
    cancel: 'Отмена',
    skip: 'Пропустить',
    retry: 'Повторить',
    loading: 'Загрузка…',
    consultDoctor: 'Это не медицинский диагноз. Перед решением обратитесь к врачу.',
  },
  splash: { tagline: 'Понимайте лекарства и отчёты сразу' },
  auth: {
    title: 'Добро пожаловать в MedScan',
    subtitle: 'Сканируйте лекарства и анализы и получайте простые пояснения.',
    phone: 'Продолжить с телефоном',
    google: 'Продолжить с Google',
    email: 'Продолжить с email',
    terms: 'Продолжая, вы принимаете Условия и Политику конфиденциальности.',
  },
  home: {
    greeting: 'Здравствуйте',
    scanCta: 'Сканировать сейчас',
    scanSubtitle: 'Лекарство или анализ',
    quickTips: 'Быстрые советы',
    recentScan: 'Недавнее сканирование',
    viewAll: 'Смотреть все',
    noRecentScan: 'Пока нет сканирований',
    noRecentScanSubtitle: 'Ваше последнее сканирование появится здесь.',
    scansLeft: 'сканирований осталось сегодня',
    upgrade: 'Премиум скоро',
    tip1: 'Держите этикетку ровно и при хорошем свете.',
    tip2: 'Отчёты сканируйте по одной странице.',
    tip3: 'MedScan только объясняет — не заменяет врача.',
  },
  tabs: { home: 'Главная', scan: 'Скан', history: 'История', profile: 'Профиль' },
  profile: {
    title: 'Мой',
    subtitle: 'Профиль',
    signedIn: 'Вход выполнен',
    guest: 'Гостевой режим',
    totalScans: 'Всего сканов',
    language: 'Язык',
    settings: 'Настройки',
    notifications: 'Уведомления',
    privacy: 'Конфиденциальность',
    terms: 'Условия сервиса',
    rate: 'Оценить приложение',
    support: 'Поддержка',
    logout: 'Выйти',
    logoutConfirm: 'Выйти?',
    logoutMsg: 'Вы выйдете из аккаунта.',
    cancel: 'Отмена',
    selectLanguage: 'Выберите язык',
  },
};

const id = {
  common: {
    continue: 'Lanjut',
    cancel: 'Batal',
    skip: 'Lewati',
    retry: 'Coba lagi',
    loading: 'Memuat…',
    consultDoctor: 'Ini bukan diagnosis medis. Konsultasikan dokter sebelum keputusan kesehatan.',
  },
  splash: { tagline: 'Pahami obat & laporan Anda seketika' },
  auth: {
    title: 'Selamat datang di MedScan',
    subtitle: 'Pindai obat dan laporan lab untuk penjelasan sederhana.',
    phone: 'Lanjut dengan telepon',
    google: 'Lanjut dengan Google',
    email: 'Lanjut dengan email',
    terms: 'Dengan melanjutkan, Anda menyetujui Syarat dan Privasi.',
  },
  home: {
    greeting: 'Halo',
    scanCta: 'Pindai sekarang',
    scanSubtitle: 'Obat atau laporan lab',
    quickTips: 'Tips cepat',
    recentScan: 'Pindaian terbaru',
    viewAll: 'Lihat semua',
    noRecentScan: 'Belum ada pindaian',
    noRecentScanSubtitle: 'Pindaian terbaru Anda akan muncul di sini.',
    scansLeft: 'pindaian tersisa hari ini',
    upgrade: 'Premium segera hadir',
    tip1: 'Jaga label rata dan terang.',
    tip2: 'Untuk laporan, pindai satu halaman per kali.',
    tip3: 'MedScan hanya menjelaskan — bukan pengganti dokter.',
  },
  tabs: { home: 'Beranda', scan: 'Pindai', history: 'Riwayat', profile: 'Profil' },
  profile: {
    title: 'Profil',
    subtitle: 'Saya',
    signedIn: 'Masuk',
    guest: 'Mode tamu',
    totalScans: 'Total pindaian',
    language: 'Bahasa',
    settings: 'Pengaturan',
    notifications: 'Notifikasi',
    privacy: 'Kebijakan privasi',
    terms: 'Syarat layanan',
    rate: 'Nilai aplikasi',
    support: 'Dukungan',
    logout: 'Keluar',
    logoutConfirm: 'Keluar?',
    logoutMsg: 'Anda akan keluar dari akun.',
    cancel: 'Batal',
    selectLanguage: 'Pilih bahasa',
  },
};

const ja = {
  common: {
    continue: '続ける',
    cancel: 'キャンセル',
    skip: 'スキップ',
    retry: '再試行',
    loading: '読み込み中…',
    consultDoctor: 'これは医療診断ではありません。健康に関する判断の前に医師に相談してください。',
  },
  splash: { tagline: '薬と検査結果をすぐに理解' },
  auth: {
    title: 'MedScanへようこそ',
    subtitle: '薬や検査レポートをスキャンして、わかりやすい説明を得ましょう。',
    phone: '電話で続ける',
    google: 'Googleで続ける',
    email: 'メールで続ける',
    terms: '続けることで利用規約とプライバシーに同意したものとみなされます。',
  },
  home: {
    greeting: 'こんにちは',
    scanCta: '今すぐスキャン',
    scanSubtitle: '薬または検査レポート',
    quickTips: 'クイックヒント',
    recentScan: '最近のスキャン',
    viewAll: 'すべて表示',
    noRecentScan: 'スキャンはまだありません',
    noRecentScanSubtitle: '最新のスキャンがここに表示されます。',
    scansLeft: '本日の残りスキャン',
    upgrade: 'プレミアム近日公開',
    tip1: 'ラベルを平らに、明るい場所で。',
    tip2: 'レポートは1ページずつスキャン。',
    tip3: 'MedScanは説明のみ — 医師の代わりにはなりません。',
  },
  tabs: { home: 'ホーム', scan: 'スキャン', history: '履歴', profile: 'プロフィール' },
  profile: {
    title: 'マイ',
    subtitle: 'プロフィール',
    signedIn: 'ログイン中',
    guest: 'ゲストモード',
    totalScans: '総スキャン数',
    language: '言語',
    settings: '設定',
    notifications: '通知',
    privacy: 'プライバシーポリシー',
    terms: '利用規約',
    rate: 'アプリを評価',
    support: 'サポート',
    logout: 'ログアウト',
    logoutConfirm: 'ログアウトしますか？',
    logoutMsg: 'アカウントからログアウトします。',
    cancel: 'キャンセル',
    selectLanguage: '言語を選択',
  },
};

const ko = {
  common: {
    continue: '계속',
    cancel: '취소',
    skip: '건너뛰기',
    retry: '다시 시도',
    loading: '로딩 중…',
    consultDoctor: '이것은 의료 진단이 아닙니다. 건강 결정 전에 의사와 상담하세요.',
  },
  splash: { tagline: '약과 검사 결과를 바로 이해하세요' },
  auth: {
    title: 'MedScan에 오신 것을 환영합니다',
    subtitle: '약과 검사 보고서를 스캔하고 쉬운 설명을 받으세요.',
    phone: '전화로 계속',
    google: 'Google로 계속',
    email: '이메일로 계속',
    terms: '계속하면 약관 및 개인정보 정책에 동의하게 됩니다.',
  },
  home: {
    greeting: '안녕하세요',
    scanCta: '지금 스캔',
    scanSubtitle: '약 또는 검사 보고서',
    quickTips: '빠른 팁',
    recentScan: '최근 스캔',
    viewAll: '전체 보기',
    noRecentScan: '아직 스캔 없음',
    noRecentScanSubtitle: '최근 스캔이 여기에 표시됩니다.',
    scansLeft: '오늘 남은 스캔',
    upgrade: '프리미엄 곧 출시',
    tip1: '라벨을 평평하고 밝은 곳에 두세요.',
    tip2: '보고서는 한 페이지씩 스캔하세요.',
    tip3: 'MedScan은 설명만 합니다 — 의사를 대체하지 않습니다.',
  },
  tabs: { home: '홈', scan: '스캔', history: '기록', profile: '프로필' },
  profile: {
    title: '내',
    subtitle: '프로필',
    signedIn: '로그인됨',
    guest: '게스트 모드',
    totalScans: '총 스캔',
    language: '언어',
    settings: '설정',
    notifications: '알림',
    privacy: '개인정보 처리방침',
    terms: '서비스 약관',
    rate: '앱 평가',
    support: '지원',
    logout: '로그아웃',
    logoutConfirm: '로그아웃할까요?',
    logoutMsg: '계정에서 로그아웃됩니다.',
    cancel: '취소',
    selectLanguage: '언어 선택',
  },
};

const th = {
  common: {
    continue: 'ดำเนินการต่อ',
    cancel: 'ยกเลิก',
    skip: 'ข้าม',
    retry: 'ลองอีกครั้ง',
    loading: 'กำลังโหลด…',
    consultDoctor: 'นี่ไม่ใช่การวินิจฉัยทางการแพทย์ ปรึกษาแพทย์ก่อนตัดสินใจด้านสุขภาพ',
  },
  splash: { tagline: 'เข้าใจยาและรายงานของคุณได้ทันที' },
  auth: {
    title: 'ยินดีต้อนรับสู่ MedScan',
    subtitle: 'สแกนยาและรายงานแล็บเพื่อคำอธิบายที่เข้าใจง่าย',
    phone: 'ดำเนินการด้วยโทรศัพท์',
    google: 'ดำเนินการด้วย Google',
    email: 'ดำเนินการด้วยอีเมล',
    terms: 'การดำเนินการต่อถือว่ายอมรับข้อกำหนดและความเป็นส่วนตัว',
  },
  home: {
    greeting: 'สวัสดี',
    scanCta: 'สแกนเลย',
    scanSubtitle: 'ยาหรือรายงานแล็บ',
    quickTips: 'เคล็ดลับด่วน',
    recentScan: 'สแกนล่าสุด',
    viewAll: 'ดูทั้งหมด',
    noRecentScan: 'ยังไม่มีการสแกน',
    noRecentScanSubtitle: 'การสแกนล่าสุดจะแสดงที่นี่',
    scansLeft: 'สแกนที่เหลือวันนี้',
    upgrade: 'พรีเมียมเร็วๆ นี้',
    tip1: 'วางฉลากให้เรียบและมีแสงเพียงพอ',
    tip2: 'สำหรับรายงาน ให้สแกนทีละหน้า',
    tip3: 'MedScan อธิบายเท่านั้น — ไม่แทนที่แพทย์',
  },
  tabs: { home: 'หน้าแรก', scan: 'สแกน', history: 'ประวัติ', profile: 'โปรไฟล์' },
  profile: {
    title: 'โปรไฟล์',
    subtitle: 'ของฉัน',
    signedIn: 'เข้าสู่ระบบแล้ว',
    guest: 'โหมดแขก',
    totalScans: 'สแกนทั้งหมด',
    language: 'ภาษา',
    settings: 'การตั้งค่า',
    notifications: 'การแจ้งเตือน',
    privacy: 'นโยบายความเป็นส่วนตัว',
    terms: 'ข้อกำหนดการใช้บริการ',
    rate: 'ให้คะแนนแอป',
    support: 'สนับสนุน',
    logout: 'ออกจากระบบ',
    logoutConfirm: 'ออกจากระบบ?',
    logoutMsg: 'คุณจะออกจากบัญชี',
    cancel: 'ยกเลิก',
    selectLanguage: 'เลือกภาษา',
  },
};

export const dictionaries = {
  en,
  ur,
  ar,
  hi,
  ps,
  pa,
  sd,
  fa,
  tr,
  bn,
  zh,
  es,
  fr,
  de,
  pt,
  ru,
  id,
  ja,
  ko,
  th,
};

export function getDictionary(lang) {
  return dictionaries[lang] ?? dictionaries.en;
}

export const isRTL = () => false;