export default {
  home: {
    greeting: 'سلام',
    tip1: 'نصیحه 1: نور ښه وڅوېدونکي لپاره یاستونکی',
    tip2: 'نصیحه 2: اسناد را مستحکم او سمه وڅوې',
    tip3: 'نصیحه 3: کتنې ته وڅوې کولې دي',
    medicineBtn: 'درمل',
    medicineSub: 'پیک / سټریپ',
    reportBtn: 'راپور',
    reportSub: 'لاب / ایکس رے',
    quickTips: 'زري Tips',
  },
  camera: {
    whatScanning: 'تاسو څه اسکن کړې یاست؟',
    medicine: 'دوا',
    medicineSub: 'باندول، سټریپ، بوتل، بلیسٹر',
    medicineTip: '',
    medicineFrame: '',
    report: 'لاب رپورټ',
    reportSub: 'خون، ادرار، پاتھولوجي رپورټ',
    reportTip: '',
    reportFrame: '',
    xray: 'ایکس-رې / اسکن',
    xraySub: 'ایکس-رې، سیٹی، ام آرآئی پرینټ / فلم',
    xrayTip: '',
    xrayFrame: '',
    prescription: 'پریسکریپشن',
    prescriptionSub: 'ڈاکٹر کی دستخط / پرینٹڈ Rx',
    prescriptionTip: '',
    prescriptionFrame: '',
    medicineHint: 'اسٹریپ / بوتل لیبل صاف دکھائیں',
    reportHint: 'پوری صفحہ / فلم فریم میں آنا چاہیے',
    scanMedicine: 'دوا اسکن کریں',
    scanDocument: 'رپورٹ اسکن کریں',
    uploadGallery: 'گیلری سے اپلوڈ کریں',
  },
  result: {
    title: 'اسکن نتیجہ',
    loading: 'نتیجه تیار شوې دی...',
    errorNoImage: 'هیچ تصویر نه موندل.',
    errorApiKey: 'جیمینی API کلید گم شوی. .env کې GEMINI_API_KEY ست کړئ',
    errorAnalysis: 'تحلیل ناکام شو.',
    errorBlurry: 'تصویر کا مسئله — تصویر صاف نه یاست.',
    errorMismatchReport: 'دا لاب رپورٹ / ٹیسټ یو دی.',
    errorMismatchMedicine: 'دا دواء کا باندول / سټریپ یو دی.',
    errorChat: 'سوال پر عمل نه شو.',
    chatTitle: 'تاسو کے سوالات',
    chatPlaceholderMedicine: 'دوا کے بارے میں پوښtene...',
    chatPlaceholderReport: 'رپورٹ کے بارے میں پوښtene...',
    retryNew: 'نئی تصویر اپلوڈ کړئ',
    retrySame: 'دې تصویر سره لکه ونیئ',
    typeMedicine: 'دوا',
    typeReport: 'لاب رپورټ',
    typePrescription: 'پریسکریپشن',
    typeOther: 'دېره',
    match: '% ملات',
    aboutMedicine: 'دوا د بارے کې',
    aboutReport: 'رپورټ د سادہ معنی',
    formulaTitle: 'فرمول او اس د کار',
    formulaLabel: 'فرمول / نمک',
    howItWorks: 'دا د جسم کې څنګه کار کوي',
    whyInMedicine: 'دا کوم د دوا کې کارول کیږي',
    howToUse: 'کسی استعمال کړئ',
    priceApprox: 'تقریبی قیمت: Rs.',
    altIntro: 'مشابہ فارمولا — دیگر کمپنیاں (تقریبی)',
    alternatives: 'اختیاری ادویات',
    onPackageMedicine: 'باندول پر likha howa',
    onPackageReport: 'رپورٹ پر likha howa',
    notesMedicine: 'اهم نوٹس',
    notesReport: 'اهم نکات',
  },
  history: {
    tabs: {
      history: 'تاريخ',
    },
    emptyTitle: 'اکه هېڅ اسکن نایست',
    emptySub: 'يک دواء یا رپورٹ اسکن کړئ — دا یهه protegerه شوی',
    deleteTitle: 'اسکن حذف کړئ؟',
    deleteMessage: '{name}',
    confirmText: 'حذف کړئ',
    cancelText: 'منسوخ کړئ',
    typeReport: 'لاب رپورټ',
    typePrescription: 'پریسکریپشن',
    typeMedicine: 'دوا',
    typeOther: 'دېره',
    scan: 'اسکن',
  },
};