export default {
  tabs: {
    home: 'کور',
    history: 'تاریخ',
    profile: 'پروفایل',
  },

  home: {
    greeting: 'سلام',
    tip1: 'نکته ۱: د سم سکین لپاره ښه رڼا ډاډه کړئ',
    tip2: 'نکته ۲: سند مستحکم او هوار ونیسئ',
    tip3: 'نکته ۳: څنډې باید بشپړ ښکاره شي',
    medicineBtn: 'درمل',
    medicineSub: 'پیک / سټریپ',
    reportBtn: 'راپور',
    reportSub: 'لاب / ایکس رے',
    quickTips: 'چټک لارښوونې',
  },

  camera: {
    whatScanning: 'تاسو څه سکین کوئ؟',
    medicine: 'درمل',
    medicineSub: 'پیک، سټریپ، بوتل',
    medicineTip: 'لیبل مستقیم وساتئ، ښه رڼا، څنډې روښانه.',
    medicineFrame: 'د درملو پیک / سټریپ په چوکاټ کې وساتئ',
    report: 'لاب راپور',
    reportSub: 'وینه، پیشاب، پتولوژي راپور',
    reportTip: 'یو ځل یوه پاڼه. کاغذ هوار، لږ سیوری، متن روښانه.',
    reportFrame: 'بشپړ راپور پاڼه باید په چوکاټ کې راشي',
    xray: 'ایکس رے / سکین',
    xraySub: 'ایکس رے، CT، MRI پرنټ / فلم',
    xrayTip: 'فلم/پرنټ په هواره سطحه. له ځلیدو ډډه، بشپړ انځور پوښئ.',
    xrayFrame: 'ایکس رے / سکین فلم بشپړ په چوکاټ کې',
    prescription: 'نسخه',
    prescriptionSub: 'د ډاکټر لاس لیکلی / پرنټ شوی نسخه',
    prescriptionTip: 'پاڼه مستقیمه، لیکنه روښانه. یو ځل یوه پاڼه.',
    prescriptionFrame: 'د نسخې پاڼه په چوکاټ کې',
    medicineHint: 'سټریپ / بوتل لیبل روښانه وښایئ',
    reportHint: 'بشپړه پاڼه / فلم باید په چوکاټ کې راشي',
    scanMedicine: 'درمل سکین کړئ',
    scanDocument: 'سند سکین کړئ',
    uploadGallery: 'له ګالري څخه اپلوډ',
  },

  result: {
    title: 'د سکین پایله',
    loading: 'پایله چمتو کیږي...',
    errorNoImage: 'هیڅ انځور ونه موندل شو.',
    errorApiKey: 'Gemini API key نشته. په .env کې GEMINI_API_KEY وټاکئ',
    errorAnalysis: 'تحلیل ناکام شو.',
    errorBlurry: 'د انځور ستونزه — عکس روښانه نه دی.',
    errorMismatchReport: 'دا د لاب راپور / ازموینه ښکاري.',
    errorMismatchMedicine: 'دا د درملو پیک / سټریپ ښکاري.',
    errorChat: 'پوښتنه پروسس نشوه.',
    chatTitle: 'ستاسو پوښتنې',
    chatPlaceholderMedicine: 'د دې درملو په اړه وپوښتئ...',
    chatPlaceholderReport: 'د دې راپور په اړه وپوښتئ...',
    retryNew: 'نوی انځور اپلوډ کړئ',
    retrySame: 'ورته انځور سره بیا هڅه',
    typeMedicine: 'درمل',
    typeReport: 'لاب راپور',
    typePrescription: 'نسخه',
    typeOther: 'نور',
    match: '% میچ',
    aboutMedicine: 'د دې درملو په اړه',
    aboutReport: 'د راپور ساده معنا',
    formulaTitle: 'فارمول او دا څنګه کار کوي',
    formulaLabel: 'فارمول / مالګه',
    howItWorks: 'دا فارمول څنګه کار کوي',
    whyInMedicine: 'په دې درملو کې ولې کارول کیږي',
    howToUse: 'څنګه وکاروئ',
    priceApprox: 'تقریبي قیمت: روپۍ',
    altIntro: 'ورته / مشابه فارمول — نور شرکتونه (تقریباً)',
    alternatives: 'بدیل درمل',
    onPackageMedicine: 'په بسته بندۍ لیکل شوي',
    onPackageReport: 'په راپور لیکل شوي',
    notesMedicine: 'مهم یادښتونه',
    notesReport: 'مهم ټکي',
    unknown: 'نامعلوم',
    noScanYet: 'تر اوسه هیڅ سکین نشته',
  },

  history: {
    tabs: {
      history: 'تاریخ',
    },
    emptyTitle: 'تر اوسه هیڅ سکین نشته',
    emptySub: 'درمل یا راپور سکین کړئ — دلته به خوندي شي',
    deleteTitle: 'سکین ړنګ کړئ؟',
    deleteMessage: '{name}',
    confirmText: 'ړنګول',
    cancelText: 'لغوه',
    typeReport: 'لاب راپور',
    typePrescription: 'نسخه',
    typeMedicine: 'درمل',
    typeOther: 'نور',
    scan: 'سکین',
  },

  profile: {
    title: 'زما',
    subtitle: 'پروفایل',
    signedIn: 'ننوتي',
    guest: 'میلمه حالت',
    totalScans: 'ټول سکینونه',
    language: 'ژبه',
    selectLanguage: 'ژبه وټاکئ',
    settings: 'ترتیبات',
    notifications: 'خبرتیاوې',
    privacy: 'د محرمیت تګلاره',
    terms: 'د خدمت شرایط',
    rate: 'اپلیکیشن درجه کړئ',
    support: 'ملاتړ',
    logout: 'وتل',
    logoutConfirm: 'وتل؟',
    logoutMsg: 'تاسو به له خپل حساب څخه ووځئ.',
    cancel: 'لغوه',
  },
};