export default {
  home: {
    greeting: 'السلام علیکم',
    tip1: 'تپ 1: درست اسکن کے لیے اچھی روشنی یقینی بنائیں',
    tip2: 'تپ 2: دستاویز کو مستحکم اور برابر رکھیں',
    tip3: 'تپ 3: किनारों کو مکمل طور پر مرئی یقینی بنائیں',
    medicineBtn: 'دوا',
    medicineSub: 'پیک / سٹریپ',
    reportBtn: 'رپورٹ',
    reportSub: 'لاب / ایکس-ری',
    quickTips: 'جلدی ٹپس',
  },
  camera: {
    whatScanning: 'آپ کیا اسکن کر رہے ہیں؟',
    medicine: 'دوا',
    medicineSub: 'پیک، سٹریپ، بوتل، بلیسٹر',
    medicineTip: '',
    medicineFrame: '',
    report: 'لاب رپورٹ',
    reportSub: 'خون، ادرار، पैथولوجي رپورٹ',
    reportTip: '',
    reportFrame: '',
    xray: 'ایکس-ری / اسکن',
    xraySub: 'ایکس-ری، سیٹی، ام آرآئی پرینٹ / فلم',
    xrayTip: '',
    xrayFrame: '',
    prescription: 'پریسکریپشن',
    prescriptionSub: 'ڈاکٹر کی دستخط / پرینٹڈ Rx',
    prescriptionTip: '',
    prescriptionFrame: '',
    medicineHint: 'اسٹریپ / بوتل لیبل صاف دکھائیں',
    reportHint: 'پوری صفحہ / فلم فریم میں آنا چاہیے',
    scanMedicine: 'دوا اسکن کریں',
    scanDocument: 'رپورٹ اسکن کریں',
    uploadGallery: 'گیلری سے اپلوڈ کریں',
  },
  result: {
    title: 'اسکن نتیجہ',
    loading: 'نتیjah تیار کیا جا رہا ہے...',
    errorNoImage: 'کoi تصویر نہیں ملی۔',
    errorApiKey: 'جیمینی API کلید گم ہے۔ .env میں GEMINI_API_KEY سیٹ کریں',
    errorAnalysis: 'تجزیہ ناکام ہوا۔',
    errorBlurry: 'تصویر کی مسئلہ — تصویر صاف نہیں ہے۔',
    errorMismatchReport: 'یہ لاب رپورٹ / ٹیسٹ جیسا دikh رہا ہے۔',
    errorMismatchMedicine: 'یہ دواء کا پیک / سٹریپ جیسا دikh رہا ہے۔',
    errorChat: 'سوال پر عمل نہیں ہو سکا۔',
    chatTitle: 'آپ کے سوالات',
    chatPlaceholderMedicine: 'دوا کے بارے میں پوچھیں...',
    chatPlaceholderReport: 'رپورٹ کے بارے میں پوچھیں...',
    retryNew: 'نیا تصویر اپلوڈ کریں',
    retrySame: 'اسی تصویر کے ساتھ دوبارہ کوشش کریں',
    typeMedicine: 'دوا',
    typeReport: 'لاب رپورٹ',
    typePrescription: 'پریسکریپشن',
    typeOther: 'دوسرا',
    match: '% ملٹا',
    aboutMedicine: 'دوا کے بارے میں',
    aboutReport: 'رپورٹ کا سادہ مطلب',
    formulaTitle: 'فارمولا اور اس کا کام',
    formulaLabel: 'فارمولا / نمک',
    howItWorks: 'یہ جسم میں کیسے کام کرتا ہے',
    whyInMedicine: 'یہ ک्यوں اس دواء میں استعمال ہوتا ہے',
    howToUse: 'kaise istemaal karein',
    priceApprox: 'تقریبی قیمت: Rs.',
    altIntro: 'مشابہ فارمولا — دیگر کمپنیاں (تقریبی)',
    alternatives: 'اختیاری ادویات',
    onPackageMedicine: 'پیکج پر likha howa',
    onPackageReport: 'رپورٹ پر likha howa',
    notesMedicine: 'اہم نوٹس',
    notesReport: 'اہم نکات',
    unknown: 'نامعلوم',
    noScanYet: 'ابھی تک کoi اسکن نہیں',
  },
  history: {
    tabs: {
      history: 'تاریخ',
    },
    emptyTitle: 'ابھی تک کoi اسکن نہیں',
    emptySub: 'ایک دواء یا رپورٹ اسکن کریں — یہ یہاں محفوظ ہو جائے گا',
    deleteTitle: 'اسکن حذف کریں؟',
    deleteMessage: '{name}',
    confirmText: 'حذف کریں',
    cancelText: 'منسوخ کریں',
    typeReport: 'لاب رپورٹ',
    typePrescription: 'پریسکریپشن',
    typeMedicine: 'دوا',
    typeOther: 'دوسرا',
    scan: 'اسکن',
  },
};