export default {
  tabs: {
    home: 'ہوم',
    history: 'تاریخ',
    profile: 'پروفائل',
  },

  home: {
    greeting: 'ہیلو',
    tip1: 'ٹپ 1: درست اسکین کے لیے اچھی روشنی یقینی بنائیں',
    tip2: 'ٹپ 2: دستاویز کو سیدھا اور مستحکم پکڑیں',
    tip3: 'ٹپ 3: کنارے مکمل طور پر نظر آنے چاہئیں',
    medicineBtn: 'دوائی',
    medicineSub: 'پیک / سٹرپ',
    reportBtn: 'رپورٹ',
    reportSub: 'لیب / ایکس رے',
    quickTips: 'فوری تجاویز',
  },

  camera: {
    whatScanning: 'آپ کیا اسکین کر رہے ہیں؟',
    medicine: 'دوائی',
    medicineSub: 'پیک، سٹرپ، بوتل، بلیسٹر',
    medicineTip: 'لیبل سیدھا رکھیں، روشنی اچھی ہو، کنارے صاف ہوں۔',
    medicineFrame: 'دوائی کا پیک / سٹرپ فریم کے اندر رکھیں',
    report: 'لیب رپورٹ',
    reportSub: 'خون، پیشاب، پیتھالوجی رپورٹ',
    reportTip: 'ایک صفحہ ایک بار۔ کاغذ سیدھا، سایہ کم، متن واضح۔',
    reportFrame: 'پوری رپورٹ فریم میں آنی چاہیے',
    xray: 'ایکس رے / اسکین',
    xraySub: 'ایکس رے، سی ٹی، ایم آر آئی پرنٹ / فلم',
    xrayTip: 'فلم/پرنٹ سیدھی سطح پر رکھیں۔ چمک سے بچیں، پوری تصویر کاور کریں۔',
    xrayFrame: 'ایکس رے / اسکین فلم مکمل طور پر فریم میں',
    prescription: 'نسخہ',
    prescriptionSub: 'ڈاکٹر کا ہاتھ لکھا / پرنٹڈ نسخہ',
    prescriptionTip: 'صفحہ سیدھا، لکھائی واضح۔ ایک صفحہ ایک بار۔',
    prescriptionFrame: 'نسخہ صفحہ فریم کے اندر',
    medicineHint: 'سٹرپ / بوتل کا لیبل واضح دکھائیں',
    reportHint: 'پورا صفحہ / فلم فریم کے اندر آئے',
    scanMedicine: 'دوائی اسکین کریں',
    scanDocument: 'دستاویز اسکین کریں',
    uploadGallery: 'گیلری سے اپلوڈ',
  },

  result: {
    title: 'اسکین نتیجہ',
    loading: 'نتیجہ تیار ہو رہا ہے...',
    errorNoImage: 'کوئی تصویر نہیں ملی۔',
    errorApiKey: 'Gemini API key غائب ہے۔ .env میں GEMINI_API_KEY سیٹ کریں',
    errorAnalysis: 'تجزیہ ناکام ہو گیا۔',
    errorBlurry: 'تصویر کا مسئلہ — فوٹو واضح نہیں۔',
    errorMismatchReport: 'یہ لیب رپورٹ / ٹیسٹ لگتی ہے۔',
    errorMismatchMedicine: 'یہ دوائی کا پیک / سٹرپ لگتا ہے۔',
    errorChat: 'سوال پروسیس نہیں ہو سکا۔',
    chatTitle: 'آپ کے سوالات',
    chatPlaceholderMedicine: 'اس دوائی کے بارے میں پوچھیں...',
    chatPlaceholderReport: 'اس رپورٹ کے بارے میں پوچھیں...',
    retryNew: 'نئی تصویر اپلوڈ کریں',
    retrySame: 'اسی تصویر سے دوبارہ کوشش',
    typeMedicine: 'دوائی',
    typeReport: 'لیب رپورٹ',
    typePrescription: 'نسخہ',
    typeOther: 'دیگر',
    match: '% میچ',
    aboutMedicine: 'اس دوائی کے بارے میں',
    aboutReport: 'رپورٹ کا سادہ مطلب',
    formulaTitle: 'فارمولا اور یہ کیسے کام کرتا ہے',
    formulaLabel: 'فارمولا / سالٹ',
    howItWorks: 'یہ فارمولا کیسے کام کرتا ہے',
    whyInMedicine: 'اس دوائی میں یہ کیوں استعمال ہوتا ہے',
    howToUse: 'استعمال کا طریقہ',
    priceApprox: 'تقریبی قیمت: روپے',
    altIntro: 'اسی / ملتا جلتا فارمولا — دوسری کمپنیاں (تقریباً)',
    alternatives: 'متبادل دوائیں',
    onPackageMedicine: 'پیکجنگ پر لکھا ہوا',
    onPackageReport: 'رپورٹ پر لکھا ہوا',
    notesMedicine: 'اہم نوٹس',
    notesReport: 'اہم باتیں',
    unknown: 'نامعلوم',
    noScanYet: 'ابھی کوئی اسکین نہیں',
  },

  history: {
    tabs: {
      history: 'تاریخ',
    },
    emptyTitle: 'ابھی کوئی اسکین نہیں',
    emptySub: 'دوائی یا رپورٹ اسکین کریں — یہاں محفوظ ہو جائے گی',
    deleteTitle: 'اسکین ڈیلیٹ کریں؟',
    deleteMessage: '{name}',
    confirmText: 'ڈیلیٹ',
    cancelText: 'منسوخ',
    typeReport: 'لیب رپورٹ',
    typePrescription: 'نسخہ',
    typeMedicine: 'دوائی',
    typeOther: 'دیگر',
    scan: 'اسکین',
  },

  profile: {
    title: 'میرا',
    subtitle: 'پروفائل',
    signedIn: 'سائن ان',
    guest: 'مہمان موڈ',
    totalScans: 'کل اسکینز',
    language: 'زبان',
    selectLanguage: 'زبان منتخب کریں',
    settings: 'ترتیبات',
    notifications: 'اطلاعات',
    privacy: 'پرائیویسی پالیسی',
    terms: 'شرائط و ضوابط',
    rate: 'ایپ ریٹ کریں',
    support: 'سپورٹ',
    logout: 'لاگ آؤٹ',
    logoutConfirm: 'لاگ آؤٹ؟',
    logoutMsg: 'آپ اپنے اکاؤنٹ سے سائن آؤٹ ہو جائیں گے۔',
    cancel: 'منسوخ',
  },
};